language: smalltalk
sudo: false

smalltalk:
  - Squeak-5.1
  - Squeak-5.2
  - Squeak-trunk

matrix:
    allow_failures:
      - smalltalk: Squeak-trunk
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  file_glob: true
  file:
    - backend/target/backend-*.jar
  skip_cleanup: true
  draft: false
  prerelease: false
  on:
    all_branches: true
